#League Configuration
#Developed by the MelonCraft Network
#Authors: BioSmasher (Gary Qian)
#         DBeck43 (Daniel Beck)


#############################
#DO NOT TOUCH CONFIG VERSION!
config-version: 1
#############################




#############################
#Basic Options
maintain-day: true

main-world-generator: CleanroomGenerator:1,bedrock,10,stone,1,dirt,1,grass

use-SQL: true
database-host:
database-port:
database-name:
SQL-username:
SQL-passsword:


#############################
#LOBBY SETTINGS

#Lobby location to select teams and choose champions
blue-lobby:
    x: 
    y: 
    z: 
    pitch: 
    yaw: 
purple-lobby:
    x: 
    y: 
    z: 
    pitch: 
    yaw: 
 
##############################
#Spawn Settings

#distance from spawn players are able to move on death.
spawn-radius: 5.5

#Spawn/recall location
blue-spawn:
    x: 
    y: 
    z: 
    pitch: 
    yaw: 
purple-spawn:
    x: 
    y: 
    z: 
    pitch: 
    yaw: 


#Coordinates of the Team switcher blocks
blue-switcher:
    x: 
    y: 
    z: 
purple-switcher:
    x: 
    y: 
    z: 
        
        
#Coordinates of the Nexuses
blue-nexus:
    x: 
    y: 
    z: 
purple-nexus:
    x: 
    y: 
    z: 



#################################################################################
#Height of the turret (will include this many bocks below the center as the turret Body)
turret-height: 
    
turret-range: 11.2
    
#TURRET CENTERS
#These are the coordinates of the top center block of the turret.    
#Blue MID
blueMid1:
    x: 
    y: 
    z: 
blueMid2:
    x: 
    y: 
    z: 
blueMid3:
    x: 
    y: 
    z: 
#Blue TOP        
blueTop1:
    x: 
    y: 
    z: 
blueTop2:
    x: 
    y: 
    z: 
blueTop3:
    x: 
    y: 
    z: 
#Blue BOT      
blueBot1:
    x: 
    y: 
    z: 
blueBot2:
    x: 
    y: 
    z: 
blueBot3:
    x: 
    y: 
    z: 
        
blueNexus1:
    x: 
    y: 
    z: 
blueNexus2:
    x: 
    y: 
    z: 


#PURPLE TURRETS
#Purple Mid
purpleMid1:
    x: 
    y: 
    z: 
purpleMid2:
    x: 
    y: 
    z: 
purpleMid3:
    x: 
    y: 
    z: 
#Purple TOP        
purpleTop1:
    x: 
    y: 
    z: 
purpleTop2:
    x: 
    y: 
    z: 
purpleTop3:
    x: 
    y: 
    z: 
#Purple BOT      
purpleBot1:
    x: 
    y: 
    z: 
purpleBot2:
    x: 
    y: 
    z: 
purpleBot3:
    x: 
    y: 
    z: 
        
purpleNexus1:
    x: 
    y: 
    z: 
purpleNexus2:
    x: 
    y: 
    z: 
