name: League
main: com.meloncraft.league.League
version: 1.0
commands:
   l:
      description: general command
      usage: /l
      permission: 
      permission-message: Test permission message
   forcestart:
      description: Forcestarts the game
      usage: /l
      permission: 
      permission-message: Test permission message
   team:
      description: Checks your team
      usage: /team
      permission: 
      permission-message: Test permission message
   randomchampion:
      description: sets you to a random champion
      usage: /randomchampion
      permission: 
      permission-message: Test permission message
   setclock:
      description: sets clock to given time (sec)
      usage: /setclock <seconds>
      permission: 
      permission-message: Test permission message
   recall:
      description: Recalls to the spawn pool
      usage: /recall
      permission: 
      permission-message: Test permission message
   fixturrets:
      description: Fixes turrets
      usage: /fixturrets
      permission: 
      permission-message: Test permission message
   shutdown:
      description: shuts down the server without saving map
      usage: /shutdown
      permission: 
      permission-message: Test permission message
   #team:
      #description: Adds friend to your team.
      #usage: /team
      #permission: proximityspawner.team
      #permission-message: You don't have proximityspawner.team
#depend: [ProtocolLib]