name: League
main: com.meloncraft.league.League
version: 1.0
commands:
   l:
      description: Spawns zombies around players.
      usage: /l
      permission: league.version
      permission-message: You don't have league.version
   #team:
      #description: Adds friend to your team.
      #usage: /team
      #permission: proximityspawner.team
      #permission-message: You don't have proximityspawner.team
#depend: [ProtocolLib]