name: League
main: com.meloncraft.league.League
version: 1.0
commands:
   l:
      description: general command
      usage: /l
      permission: 
      permission-message: Test permission message
   forcestart:
      description: Forcestarts the game
      usage: /l
      permission: 
      permission-message: Test permission message
   team:
      description: Checks your team
      usage: /team
      permission: 
      permission-message: Test permission message
   #team:
      #description: Adds friend to your team.
      #usage: /team
      #permission: proximityspawner.team
      #permission-message: You don't have proximityspawner.team
#depend: [ProtocolLib]